export const LEADERBOARD_SCORE_TYPES: string[] = [
  'Laptime',
  'DriftPoints',
  'UGCPoints',
  'XP',
  'SpeedTrap',
  'AverageSpeedZone',
  'PhotoCollection',
  'BarnFindDiscovery',
  'DiscountSignCollection',
  'RoadDiscovery',
  'RaceEncounter',
  'BucketListCompleted',
  'BucketListBiggerIsBetter',
  'BucketListSmallerIsBetter',
  'SkillsCombo',
  'LeaguePoints',
  'TotalEventTime',
  'DangerSign',
  'DriftZone',
  'FreeRoamPoints',
  'PointsOfInterestDiscovered',
  'BeautySpotsDiscovered',
  'MountainRoadDiscovery',
  'MountainDiscountSignCollection',
  'MountainPointsOfInterestDiscovered',
  'MountainFreeroamPoints',
  'IslandRoadDiscovery',
  'IslandDiscountSignCollection',
  'IslandPointsOfInterestDiscovered',
  'IslandFreeroamPoints',
  'TrueSkillRacingOnly',
  'TrueSkillPlaygroudGamesOnly',
  'TrueSkillAnythingGoes',
  'TrailblazerStunt',
  'SavageRoadsDiscovered',
  'SavageBeautySpotsDiscovered',
  'SavageTreasureChestsSmashed',
  'SavagePointsOfInterestDiscovered',
  'SavageRewardBoardsDiscovered',
  'TrueSkillSoloAdventure',
  'RedRoadsDiscovered',
  'RedLandmarksDiscovered',
  'RedBeautySpotsDiscovered',
  'RedDiscountBoardsSmashed',
  'RedBrickChallengesCompleted',
  'RedConditionalCollectablesSmashed',
  'RedCollectablesEverywhereSmashed',
  'RedEventsDiscovered',
  'RedConditionalCollectablesNightSmashed',
  'RedConditionalCollectablesRainSmashed',
  'RedConditionalCollectablesBonus1Smashed',
  'RedConditionalCollectablesBonus3Smashed',
  'TrueSkillDriftAdventure',
  'TridentRoadsDiscovered',
  'TridentLandmarksDiscovered',
  'TridentBeautySpotsDiscovered',
  'TridentDiscountBoardsSmashed',
  'TridentEventsDiscovered',
  'TridentStuntRuns',
];

export const LEADERBOARD_SCOREBOARD_TYPES: string[] = [
  'Circuit', //NA
  'Drift',
  'Rivals',
  'Ambient',
  'ClassSpecificEvent', //NA - maybe?
  'NonClassSpecificEvent', // intent was pivot id = event id,
  'WeeklyXp',
  'ClubXP',
  'ZoneEvent',
  'League', //NA
  'CareerEvent', //NA
  'BucketListChallenge', //NA
  'UGCBucketListChallenge', //NA
  'HorizonTrueSkill', //NA
  'HorizonTeamTrueSkill', //NA
];

export const LEADERBOARD_VIEWS: string[] = [
  'All',
  'NearbyMe',
  'Friends',
  'Favorites',
  'Club',
  'FriendsAndClub',
  'FriendsAndClubRelative',
  'MiniBoard',
  'Region',
  'BodyFamily',
  'Hardcore',
  'EnumCount',
];
