trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '12.x'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Web-Scrutineer/Scrutineer-Client'
- task: CmdLine@2
  inputs:
    script: 'npm run dev:build'
    workingDirectory: 'Web-Scrutineer/Scrutineer-Client'


