# The purpose of this pipeline is to verify the state of
# packages/StewardClient code being merged into main.
# It is for use on PRs.
# 
# What it does:
# - Check that StewardClient project will build
# - Check that StewardClient project complies with linters
# - Runs StewardClient unit tests and produces a summary

trigger: none

name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)

variables:
- template: 'infra/azure-pipelines/dotnet-core/dotnet-variables.yml'

pool:
  vmImage: $(VM_IMAGE)

stages:
- stage: API_Prepare_Directory
  displayName: Prepare Directory (API)
  jobs:
  - template: infra/azure-pipelines/dotnet-core/stage-api-prepare.template.yml
    parameters:
      workingDirectory: packages/StewardApi

- stage: API_Test
  displayName: Test (API)
  jobs:
  - template: infra/azure-pipelines/dotnet-core/stage-api-verify.template.yml
    parameters:
      workingDirectory: packages/StewardApi