name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)

variables:
  - template: 'infra/azure-pipelines/node/ui-variables.yml'

stages:
- stage: UI_Prepare_Directory
  displayName: Prepare Directory (UI)
  jobs:
  - template: infra/azure-pipelines/node/stage-prepare-ui.template.yml
    parameters:
      workingDirectory: packages/StewardClient
- stage: UI_Test
  displayName: Test (UI)
  jobs:
  - template: infra/azure-pipelines/node/stage-test-ui.template.yml
    parameters:
      workingDirectory: packages/StewardClient