trigger: none

name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)

variables:
  - template: 'infra/azure-pipelines/node/ui-variables.yml'

pool:
  vmImage: ubuntu-20.04

stages:
- stage: UI_Prepare_Directory
  displayName: Prepare Directory (UI)
  jobs:
  - template: infra/azure-pipelines/node/stage-prepare-ui.template.yml
    parameters:
      workingDirectory: packages/StewardClient
      dropName: $(DROP_NAME)
- stage: UI_Test
  displayName: Test (UI)
  jobs:
  - template: infra/azure-pipelines/node/stage-verify-ui.template.yml
    parameters:
      workingDirectory: packages/StewardClient
      dropName: $(DROP_NAME)