# This file runs a test build as a single parallel job.
# It is intended to be run only after a `yarn` cache is made.

parameters:
- name: 'workingDirectory'
  displayName: "Path to a working directory where yarn can be run. Like 'packages/StewardClient'."
  type: string
- name: 'distDirectory'
  displayName: "Path to a directory where files will be after build. Like 'packages/StewardClient/dist'."
  type: string
- name: 'distArtifactName'
  displayName: "Name of artifact to publish from dist directory. Like 'ui-drop-dev'."
  type: string

jobs:
- job: UI_Static_Build
  displayName: Static Build
  steps:
  - template: load-yarn-project.template.yml
    parameters:
      workingDirectory: ${{parameters.workingDirectory}}
  
  - task: Bash@3
    displayName: Determine target environment
    inputs:
      workingDirectory: ${{parameters.workingDirectory}}
      targetType: 'inline'
      script: |
        STATIC_ENV=$(echo "$(System.PullRequest.SourceBranch)" | grep -Po '(?<=refs/heads/).*?(?=/)')
        echo "$(System.PullRequest.SourceBranch) -> $STATIC_ENV"
        echo "##vso[task.setvariable variable=static_env]$STATIC_ENV"

  - task: Bash@3
    displayName: Static Build (Dev)
    inputs:
      workingDirectory: ${{parameters.workingDirectory}}
      targetType: 'inline'
      script: yarn run build:dev-static-pr

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ${{parameters.distArtifactName}}'
    inputs:
      PathtoPublish: ${{parameters.distDirectory}}
      ArtifactName: ${{parameters.distArtifactName}}

  # - task: AzureStaticWebApp@0
  #   displayName: Publish Dev to Static Staging Environment
  #   continueOnError: true
  #   inputs:
  #     app_location: ${{parameters.distDirectory}}
  #     azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
  #     deployment_environment: $(static_env)
  #     skip_app_build: true
  #     skip_api_build: true