jobs:
- job: Job_2
  displayName: Angular (Lint & Test)
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    submodules: true
    persistCredentials: True
  - task: CmdLine@2
    displayName: Git Command Setup
    inputs:
      script: >-
        git fetch --recurse-submodules=no
  - task: Cache@2
    displayName: Cache node_modules
    inputs:
      key: '"yarn" | "$(Agent.OS)" | **/yarn.lock'
      path: $(Build.Repository.LocalPath)/packages/StewardClient/node_modules
      restoreKeys: >-
        yarn | "$(Agent.OS)"

        yarn
  - task: NodeTool@0
    displayName: Use Node Version
    inputs:
      versionSpec: 18.x
  - task: npmAuthenticate@0
    displayName: Authenticate for private NPM packages copy
    inputs:
      workingFile: packages/StewardClient/.npmrc
  - task: Bash@3
    displayName: Changelog Must Be Modified
    inputs:
      targetType: inline
      script: yarn run check:ado:changelog-is-modified
      workingDirectory: packages/StewardClient/
      failOnStderr: true
  - task: CmdLine@2
    displayName: yarn install copy
    condition: succeededOrFailed()
    retryCountOnTaskFailure: 3
    inputs:
      script: yarn --frozen-lockfile --network-timeout 1000000
      workingDirectory: packages/StewardClient/
  - task: CmdLine@2
    displayName: Lint Check (Angular)
    condition: succeededOrFailed()
    inputs:
      script: >
        yarn run lint
      workingDirectory: packages/StewardClient/
  - task: CmdLine@2
    displayName: Lint Check (Prettier)
    condition: succeededOrFailed()
    inputs:
      script: >
        yarn run check:prettier
      workingDirectory: packages/StewardClient/