# The purpose of this pipeline is to publish a non-preview Nuget package.
#
# What it does:
# - Check that Documentation-Analyzer projects will build
# - Packs and publishes the Turn10.Analyzer.Documentation nuget with the configured <Version>

trigger:
  - main

name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)

variables:
  - template: "dotnet-core/dotnet-variables.yml"

pool:
  vmImage: $(VM_IMAGE)

jobs:
  - template: "dotnet-core/nuget/job-nuget-publish.template.yml"
    parameters:
      workingDirectory: packages/Analyzer-Documentation
      nugetName: Turn10.Analyzer.Documentation
      prerelease: false
