using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Graph;
using Microsoft.TeamFoundation.SourceControl.WebApi;
using StewardGitApi;
using Swashbuckle.AspNetCore.Annotations;
using Turn10.Data.Common;
using Turn10.LiveOps.StewardApi.Authorization;
using Turn10.LiveOps.StewardApi.Contracts.Exceptions;
using Turn10.LiveOps.StewardApi.Contracts.Steelhead.WelcomeCenter;
using Turn10.LiveOps.StewardApi.Filters;
using Turn10.LiveOps.StewardApi.Helpers;
using Turn10.LiveOps.StewardApi.Providers.Steelhead.ServiceConnections;
using static Turn10.LiveOps.StewardApi.Helpers.Swagger.KnownTags;

namespace Turn10.LiveOps.StewardApi.Controllers.V2.Steelhead.WelcomeCenter
{
    /// <summary>
    ///     Controller for managing localization strings in Pegasus.
    /// </summary>
    [Route("api/v{version:apiVersion}/title/steelhead/localization")]
    [AuthorizeRoles(UserRole.GeneralUser, UserRole.LiveOpsAdmin)]
    [LogTagTitle(TitleLogTags.Steelhead)]
    [ApiController]
    [ApiVersion("2.0")]
    [Tags(Title.Steelhead, Topic.Pegasus)]
    public class LocalizationStringController : V2SteelheadControllerBase
    {
        private readonly ISteelheadPegasusService steelheadPegasusService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="LocalizationStringController"/> class.
        /// </summary>
        public LocalizationStringController(ISteelheadPegasusService steelheadPegasusService)
        {
            steelheadPegasusService.ShouldNotBeNull(nameof(steelheadPegasusService));

            this.steelheadPegasusService = steelheadPegasusService;
        }

        /// <summary>
        ///     Gets localization string categories.
        /// </summary>
        [HttpGet("categories")]
        [SwaggerResponse(200, type: typeof(List<string>))]
        [LogTagDependency(DependencyLogTags.Pegasus)]
        [LogTagAction(ActionTargetLogTags.System, ActionAreaLogTags.Lookup | ActionAreaLogTags.Meta)]
        public async Task<IActionResult> GetLocalizationCategories()
        {
            var categories = await this.steelheadPegasusService.GetLocalizationCategoriesAsync().ConfigureAwait(true);

            return this.Ok(categories);
        }

        /// <summary>
        ///     Submits new localized strings to Pegasus.
        /// </summary>
        [HttpPost("{path}")]
        [AuthorizeRoles(UserRole.LiveOpsAdmin)]
        [SwaggerResponse(200, type: typeof(Contracts.Git.PullRequest))]
        [LogTagDependency(DependencyLogTags.Pegasus)]
        [LogTagAction(ActionTargetLogTags.System, ActionAreaLogTags.Lookup | ActionAreaLogTags.Update | ActionAreaLogTags.Meta)]
        public async Task<IActionResult> WriteLocalizedStringsToPegasus(string path, [FromBody] IEnumerable<LocalizedStringBridge> localizedStringBridge)
        {
            if (string.IsNullOrEmpty(path))
            {
                throw new BadRequestStewardException($"Localized string path is null or empty: {path}");
            }

            path = "/Source/Localization/Localization-MOTD.xml";
            CommitRefProxy change = await this.steelheadPegasusService.WriteLocalizedStringsToPegasusAsync(path, localizedStringBridge).ConfigureAwait(true);

            GitPush pushed = await this.steelheadPegasusService.CommitAndPushAsync(new CommitRefProxy[] { change }).ConfigureAwait(true);
            _ = await this.steelheadPegasusService.RunFormatPipelineAsync(pushed).ConfigureAwait(true);

            var user = this.User.UserClaims();
            var pullRequestTitle = $"Adds new localized strings to steward. Author: {user.EmailAddress}";
            var pullRequestDescription = $"- Autogenerated pull request\n\t- Edited on {DateTime.UtcNow:u} (UTC)";

            var pullrequest = await this.steelheadPegasusService.CreatePullRequestAsync(pushed, pullRequestTitle, pullRequestDescription).ConfigureAwait(true);

            return this.Ok(pullrequest);
        }
    }
}
